# Generated by Django 4.1.2 on 2022-10-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagename', models.CharField(max_length=10)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
